// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IconBi: exclamationCircleFill': typeof import('~icons/bi/exclamation-circle-fill')['default']
    'IconBi:exclamationCircleFill': typeof import('~icons/bi/exclamation-circle-fill')['default']
    IconClarity: timesLine': typeof import('~icons/clarity/times-line')['default']
    'IconClarity:timesCircleSolid': typeof import('~icons/clarity/times-circle-solid')['default']
    'IconClarity:timesLine': typeof import('~icons/clarity/times-line')['default']
    IconFaSolid: ellipsisV': typeof import('~icons/fa-solid/ellipsis-v')['default']
    'IconFaSolid:ellipsisV': typeof import('~icons/fa-solid/ellipsis-v')['default']
    IconIc: roundLogout': typeof import('~icons/ic/round-logout')['default']
    'IconIc:baselineContentCopy': typeof import('~icons/ic/baseline-content-copy')['default']
    'IconIc:roundLogout': typeof import('~icons/ic/round-logout')['default']
    IconMdi: logoutVariant': typeof import('~icons/mdi/logout-variant')['default']
    'IconMdi:alertCircleCheck': typeof import('~icons/mdi/alert-circle-check')['default']
    'IconMdi:githubFace': typeof import('~icons/mdi/github-face')['default']
    'IconMdi:logoutVariant': typeof import('~icons/mdi/logout-variant')['default']
    IconTabler: externalLink': typeof import('~icons/tabler/external-link')['default']
    'IconTabler:externalLink': typeof import('~icons/tabler/external-link')['default']
    IconUil: times': typeof import('~icons/uil/times')['default']
    'IconUil:angleDown': typeof import('~icons/uil/angle-down')['default']
    'IconUil:apps': typeof import('~icons/uil/apps')['default']
    'IconUil:bars': typeof import('~icons/uil/bars')['default']
    'IconUil:clock': typeof import('~icons/uil/clock')['default']
    'IconUil:laptop': typeof import('~icons/uil/laptop')['default']
    'IconUil:moon': typeof import('~icons/uil/moon')['default']
    'IconUil:signout': typeof import('~icons/uil/signout')['default']
    'IconUil:sun': typeof import('~icons/uil/sun')['default']
    'IconUil:times': typeof import('~icons/uil/times')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }

}
